"""Golden-file tests for the generated catalogues.

``datasets/DATASETS.md`` and ``docs/RUNS.md`` are outputs of
``scripts/gen_catalog_md.py``, so the thing worth pinning is their exact bytes:
a catalogue that renders differently on every run cannot be committed, and one
that renders *wrongly* is worse than none at all. The expected pages below are
written out in full — small enough to read, specific enough that any change to
the layout has to be made deliberately here first.
"""

import json
import sys
from pathlib import Path

import pytest

SCRIPTS_DIR = Path(__file__).resolve().parents[1] / "scripts"
sys.path.insert(0, str(SCRIPTS_DIR))

import gen_catalog_md  # noqa: E402 - needs the sys.path line above

EVAL_RUN = "act__grasp_cube_v1__20260812-2200__1234567"
TRAIN_RUN = "act__grasp_cube_v1__20260812-1000__1234567"

EXPECTED_DATASETS_MD = """\
# Datasets

Generated by `scripts/gen_catalog_md.py` from `datasets/raw/*/manifest.json`.
Do not edit by hand — regenerate it.

| Dataset | Objects | Attempts | Successes | Frames | Success rate | LeRobot | Dataset id | Git | Created | Preview |
|---|---|---|---|---|---|---|---|---|---|---|
| `grasp_cube_dev` | cube_3cm | 54 | 50 | 6021 | 92.6% | — | `aaaaaaaaaaaa` | `d0e26f3` | 2026-08-11 | — |
| `grasp_cube_v1` | cube_3cm, cylinder_3cm | 1042 | 1000 | 121344 | 96.0% | yes | `bbbbbbbbbbbb` | `1234567`* | 2026-08-12 | [gif](../media/datasets/grasp_cube_v1.gif) |

`Git` is the commit the dataset was generated at; a trailing `*` marks a dirty tree.
"""

EXPECTED_RUNS_MD = f"""\
# Runs

Generated by `scripts/gen_catalog_md.py` from `runs/*/*/run.json`.
Do not edit by hand — regenerate it.

| Run | Kind | Dataset | Dataset id | Result | Git | Created | Preview |
|---|---|---|---|---|---|---|---|
| `{EVAL_RUN}` | eval | `grasp_cube_v1` | `bbbbbbbbbbbb` | Wilson LB95 0.81 | `1234567` | 2026-08-13 | [gif](../media/eval/{EVAL_RUN}.gif) |
| `{TRAIN_RUN}` | train | `grasp_cube_v1` | `bbbbbbbbbbbb` | — | `1234567` | 2026-08-12 | — |
"""


def _write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


@pytest.fixture
def catalogue_tree(tmp_path: Path) -> Path:
    """A repository-shaped tree with two datasets and two runs.

    ``grasp_cube_v1`` is created first so that a generator relying on
    filesystem order rather than sorting would emit the rows the wrong way
    round.
    """
    _write_json(
        tmp_path / "datasets" / "raw" / "grasp_cube_v1" / "manifest.json",
        {
            "dataset_name": "grasp_cube_v1",
            "dataset_id": "b" * 64,
            "counts": {"attempts": 1042, "successes": 1000, "failures": 42, "frames": 121344},
            "success_rate": 1000 / 1042,
            "env": {"objects": ["cube_3cm", "cylinder_3cm"], "numpy": "2.4.4"},
            "git": {"sha": "1234567abcdef", "dirty": True},
            "created": "2026-08-12T22:01:00Z",
        },
    )
    _write_json(
        tmp_path / "datasets" / "raw" / "grasp_cube_dev" / "manifest.json",
        {
            "dataset_name": "grasp_cube_dev",
            "dataset_id": "a" * 64,
            "counts": {"attempts": 54, "successes": 50, "failures": 4, "frames": 6021},
            "success_rate": 50 / 54,
            "env": {"objects": ["cube_3cm"], "numpy": "2.4.4"},
            "git": {"sha": "d0e26f3aaaaaaaa", "dirty": False},
            "created": "2026-08-11T09:15:00Z",
        },
    )
    # Converted copy and preview exist for v1 only.
    (tmp_path / "datasets" / "lerobot" / "grasp_cube_v1").mkdir(parents=True)
    (tmp_path / "media" / "datasets").mkdir(parents=True)
    (tmp_path / "media" / "datasets" / "grasp_cube_v1.gif").write_bytes(b"GIF89a")

    _write_json(
        tmp_path / "runs" / "train" / TRAIN_RUN / "run.json",
        {
            "kind": "train",
            "run_name": TRAIN_RUN,
            "dataset_name": "grasp_cube_v1",
            "dataset_id": "b" * 64,
            "git": {"sha": "1234567abcdef", "dirty": False},
            "created": "2026-08-12T10:00:00Z",
        },
    )
    _write_json(
        tmp_path / "runs" / "eval" / EVAL_RUN / "run.json",
        {
            "kind": "eval",
            "run_name": EVAL_RUN,
            "dataset_name": "grasp_cube_v1",
            "dataset_id": "b" * 64,
            "result": "Wilson LB95 0.81",
            "git": {"sha": "1234567abcdef", "dirty": False},
            "created": "2026-08-13T08:00:00Z",
        },
    )
    (tmp_path / "media" / "eval").mkdir(parents=True)
    (tmp_path / "media" / "eval" / f"{EVAL_RUN}.gif").write_bytes(b"GIF89a")
    return tmp_path


# --- Golden pages ------------------------------------------------------------


def test_datasets_page_matches_the_golden_file(catalogue_tree):
    assert gen_catalog_md.render_datasets_md(catalogue_tree) == EXPECTED_DATASETS_MD


def test_runs_page_matches_the_golden_file(catalogue_tree):
    assert gen_catalog_md.render_runs_md(catalogue_tree) == EXPECTED_RUNS_MD


def test_an_empty_repository_still_renders(tmp_path):
    assert "_No datasets yet._" in gen_catalog_md.render_datasets_md(tmp_path)
    assert "_No runs yet._" in gen_catalog_md.render_runs_md(tmp_path)


def test_a_pipe_in_a_value_cannot_break_the_table(tmp_path):
    _write_json(
        tmp_path / "datasets" / "raw" / "odd" / "manifest.json",
        {"dataset_name": "odd", "env": {"objects": ["cube|3cm"]}},
    )
    row = next(
        line
        for line in gen_catalog_md.render_datasets_md(tmp_path).splitlines()
        if line.startswith("| `odd`")
    )
    assert "cube\\|3cm" in row
    assert row.count("|") - row.count("\\|") == 12  # 11 columns, 12 delimiters


def test_missing_provenance_renders_as_a_dash(tmp_path):
    _write_json(tmp_path / "runs" / "eval" / "bare" / "run.json", {})
    row = next(
        line
        for line in gen_catalog_md.render_runs_md(tmp_path).splitlines()
        if line.startswith("| `bare`")
    )
    # Only the run's own directory tells us anything; the rest is honest dashes.
    assert row == "| `bare` | eval | — | — | — | — | — | — |"


# --- Regeneration ------------------------------------------------------------


def test_regeneration_is_byte_identical(catalogue_tree, capsys):
    assert gen_catalog_md.main(["--root", str(catalogue_tree)]) == 0
    pages = {
        relative: (catalogue_tree / relative).read_bytes()
        for relative, _ in gen_catalog_md.CATALOGUES
    }
    assert pages[gen_catalog_md.DATASETS_MD].decode() == EXPECTED_DATASETS_MD

    capsys.readouterr()
    assert gen_catalog_md.main(["--root", str(catalogue_tree)]) == 0
    assert all(
        (catalogue_tree / relative).read_bytes() == pages[relative]
        for relative, _ in gen_catalog_md.CATALOGUES
    )
    # Nothing was rewritten the second time round.
    assert capsys.readouterr().out.count("unchanged:") == len(gen_catalog_md.CATALOGUES)


def test_check_mode_reports_a_stale_page(catalogue_tree):
    # Never generated at all.
    assert gen_catalog_md.main(["--root", str(catalogue_tree), "--check"]) == 1

    assert gen_catalog_md.main(["--root", str(catalogue_tree)]) == 0
    assert gen_catalog_md.main(["--root", str(catalogue_tree), "--check"]) == 0

    # Hand-edited, or generated before a dataset changed.
    (catalogue_tree / gen_catalog_md.DATASETS_MD).write_text("# Datasets\n", encoding="utf-8")
    assert gen_catalog_md.main(["--root", str(catalogue_tree), "--check"]) == 1
