"""Regenerate the dataset and run catalogues from machine-written provenance.

``datasets/DATASETS.md`` comes from every ``datasets/raw/*/manifest.json``, and
``docs/RUNS.md`` from every ``runs/*/*/run.json``. Both are outputs, never
inputs: nothing here is hand-maintained, so the catalogues cannot drift from
the data the way a hand-written index always eventually does.

.. code-block:: bash

    ~/isaaclab-env/bin/python scripts/gen_catalog_md.py            # write both
    ~/isaaclab-env/bin/python scripts/gen_catalog_md.py --check    # fail if stale

Deterministic and idempotent by construction: rows are sorted by name, every
value is read from a file, and nothing records the moment of generation — so
regenerating without changing a manifest reproduces the previous bytes exactly.
That is what makes ``--check`` usable as a lockfile-style test.

``run.json`` is written by the training and eval scripts; this reader expects
``kind``, ``run_name``, ``dataset_name``, ``dataset_id``, ``result`` (a short
headline string), ``git`` (``{"sha", "dirty"}``) and ``created``. Missing keys
render as an em dash rather than failing the catalogue, and the run's directory
supplies its kind and name regardless.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]

DATASETS_MD = Path("datasets/DATASETS.md")
"""Dataset catalogue, relative to the repository root."""

RUNS_MD = Path("docs/RUNS.md")
"""Run catalogue, relative to the repository root."""

EMPTY = "—"
"""Rendered stand-in for a value the provenance does not carry."""

ID_WIDTH = 12
"""Characters of a content hash shown in a table: enough to be unambiguous."""

SHA_WIDTH = 7
"""Characters of a git sha shown in a table (``git log --oneline`` width)."""


def _cell(value: Any) -> str:
    """Render one table cell, escaping the pipe that would split the row."""
    if value is None or value == "":
        return EMPTY
    return str(value).replace("|", "\\|")


def _code(value: Any, width: int | None = None) -> str:
    """Render `value` as inline code, truncated to `width`, or an em dash."""
    if not value:
        return EMPTY
    text = str(value)
    return f"`{text[:width] if width else text}`"


def _git_cell(git: Any) -> str:
    """Render a ``{"sha", "dirty"}`` block; a dirty working tree gets a star."""
    if not isinstance(git, Mapping) or not git.get("sha"):
        return EMPTY
    return _code(git["sha"], SHA_WIDTH) + ("*" if git.get("dirty") else "")


def _date(value: Any) -> str:
    """Calendar date of an ISO-8601 timestamp."""
    return _cell(str(value)[:10] if value else None)


def _table(headers: Sequence[str], rows: Sequence[Sequence[str]]) -> list[str]:
    """Markdown table as a list of lines."""
    return [
        "| " + " | ".join(headers) + " |",
        "|" + "---|" * len(headers),
        *("| " + " | ".join(row) + " |" for row in rows),
    ]


def _read_json(path: Path) -> dict[str, Any]:
    """Read one provenance file, naming it if it is unparseable."""
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise ValueError(f"{path}: {error}") from error
    if not isinstance(payload, dict):
        raise ValueError(f"{path}: expected a JSON object, got {type(payload).__name__}")
    return payload


def _block(value: Any) -> Mapping[str, Any]:
    """A nested provenance block, or an empty one when it is absent or malformed."""
    return value if isinstance(value, Mapping) else {}


def _document(title: str, source: str, lines: Sequence[str]) -> str:
    """Assemble a generated catalogue page."""
    header = [
        f"# {title}",
        "",
        f"Generated by `scripts/gen_catalog_md.py` from `{source}`.",
        "Do not edit by hand — regenerate it.",
        "",
    ]
    return "\n".join([*header, *lines, ""])


def render_datasets_md(root: Path) -> str:
    """Render ``datasets/DATASETS.md`` for the repository at `root`."""
    manifests = sorted(
        (root / "datasets" / "raw").glob("*/manifest.json"), key=lambda path: path.parent.name
    )
    rows = []
    for path in manifests:
        name = path.parent.name
        manifest = _read_json(path)
        counts = _block(manifest.get("counts"))
        objects = _block(manifest.get("env")).get("objects")
        rate = manifest.get("success_rate")
        preview = root / "media" / "datasets" / f"{name}.gif"
        rows.append(
            [
                _code(manifest.get("dataset_name", name)),
                _cell(", ".join(objects) if isinstance(objects, list) else objects),
                _cell(counts.get("attempts")),
                _cell(counts.get("successes")),
                _cell(counts.get("frames")),
                _cell(f"{rate:.1%}" if isinstance(rate, (int, float)) else None),
                "yes" if (root / "datasets" / "lerobot" / name).is_dir() else EMPTY,
                _code(manifest.get("dataset_id"), ID_WIDTH),
                _git_cell(manifest.get("git")),
                _date(manifest.get("created")),
                f"[gif](../media/datasets/{name}.gif)" if preview.is_file() else EMPTY,
            ]
        )

    if not rows:
        body = ["_No datasets yet._"]
    else:
        body = [
            *_table(
                (
                    "Dataset",
                    "Objects",
                    "Attempts",
                    "Successes",
                    "Frames",
                    "Success rate",
                    "LeRobot",
                    "Dataset id",
                    "Git",
                    "Created",
                    "Preview",
                ),
                rows,
            ),
            "",
            "`Git` is the commit the dataset was generated at; a trailing `*` marks a dirty tree.",
        ]
    return _document("Datasets", "datasets/raw/*/manifest.json", body)


def render_runs_md(root: Path) -> str:
    """Render ``docs/RUNS.md`` for the repository at `root`."""
    run_files = sorted(
        (root / "runs").glob("*/*/run.json"),
        key=lambda path: (path.parent.parent.name, path.parent.name),
    )
    rows = []
    for path in run_files:
        kind, name = path.parent.parent.name, path.parent.name
        run = _read_json(path)
        preview = root / "media" / "eval" / f"{name}.gif"
        rows.append(
            [
                _code(run.get("run_name", name)),
                _cell(run.get("kind", kind)),
                _code(run.get("dataset_name")),
                _code(run.get("dataset_id"), ID_WIDTH),
                _cell(run.get("result")),
                _git_cell(run.get("git")),
                _date(run.get("created")),
                f"[gif](../media/eval/{name}.gif)" if preview.is_file() else EMPTY,
            ]
        )

    body = (
        ["_No runs yet._"]
        if not rows
        else _table(
            ("Run", "Kind", "Dataset", "Dataset id", "Result", "Git", "Created", "Preview"), rows
        )
    )
    return _document("Runs", "runs/*/*/run.json", body)


CATALOGUES = ((DATASETS_MD, render_datasets_md), (RUNS_MD, render_runs_md))
"""Every generated page, as (path relative to the root, renderer)."""


def main(argv: Sequence[str] | None = None) -> int:
    """Regenerate (or, with ``--check``, audit) both catalogues.

    Returns:
        The process exit code: non-zero only when ``--check`` finds a page that
        does not match what the provenance says it should be.
    """
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--root", type=Path, default=REPO_ROOT, help="repository root")
    parser.add_argument(
        "--check", action="store_true", help="report stale pages instead of writing them"
    )
    args = parser.parse_args(argv)

    stale = []
    for relative, render in CATALOGUES:
        path = args.root / relative
        text = render(args.root)
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if args.check:
            if current != text:
                stale.append(relative)
            print(f"{'STALE' if current != text else 'OK'}: {relative}")
            continue
        if current == text:
            print(f"unchanged: {relative}")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote: {relative}")

    if stale:
        print(f"FAIL: {len(stale)} catalogue(s) out of date -- run scripts/gen_catalog_md.py")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
